---

- name: install kernel sources and development tooling
  yum: name={{ item }} state=present
  with_items:
    - kernel-devel
    - "@Development Tools"

- name: mount vbox guest additions iso
  shell: mount -o loop,ro /home/vagrant/vbox_guest_additions.iso /mnt
  args:
    warn: no

- name: run vbox guest additions installer
  shell: sh VBoxLinuxAdditions.run --nox11
  args:
    chdir: /mnt

- name: umount vbox guest additions
  shell: umount /mnt
  args:
    warn: no

- name: enable vbox guest additions service
  service: name=vboxadd-service.service state=started enabled=yes


...
