---

- include_tasks: scenarios/rhgs-3.3.1-rhel-7.yml
  when:
    - os_version is defined
    - os_version == "rhel-7"
    - rhgs_version is defined
    - rhgs_version == "3.3.1"

- include_tasks: scenarios/rhgs-3.3.1-centos-7.yml
  when:
    - os_version is defined
    - os_version == "centos-7"
    - rhgs_version is defined
    - rhgs_version == "3.3.1"
...
