---

- name: pre-install tendrl server components
  yum: name={{ item }} state=present
  with_items:
    - ansible
    - tendrl-ansible
    - etcd
    - libselinux-python
    - tendrl-selinux
    - tendrl-api
    - tendrl-monitoring-integration
    - carbon-selinux
    - tendrl-grafana-selinux
    - tendrl-node-agent
    - tendrl-notifier
    - tendrl-ui

- name: update all remaining packages
  yum: name=* state=latest

...
