---

- name: create ssh directory
  file:
    path: /home/vagrant/.ssh
    state: directory
    mode: 0700

- name: create ssh key pair for internal use
  shell:
    cmd: ssh-keygen -b 2048 -t rsa -f /home/vagrant/.ssh/id_rsa -q -N ""
    creates: /home/vagrant/.ssh/id_rsa

- name: change permissions on key pair
  file: path=/home/vagrant/.ssh/{{ item }} owner=vagrant group=vagrant mode=0400
  with_items:
    - id_rsa
    - id_rsa.pub

- name: fetch ssh pub key
  fetch:
    src: /home/vagrant/.ssh/id_rsa.pub
    dest: fetch/
    flat: yes

- name: fetch ssh private key
  fetch:
    src: /home/vagrant/.ssh/id_rsa
    dest: fetch/
    flat: yes

- name: add ssh key pair to authorized_keys
  authorized_key:
    user: vagrant
    key: "{{ lookup('file', 'fetch/id_rsa.pub') }}"
    state: present

...
