---

- hosts: gluster-servers

  become: true

  tasks:
    - name: add gluster repo
      yum_repository:
        name: gluster
        description: gluster repo
        baseurl: http://artifacts.ci.centos.org/gluster/nightly/release-3.12/$releasever/$basearch
        gpgcheck: no

    - name: Install GlusterFS Server
      yum:
        name: glusterfs-server
        state: present

    - name: Enable GlusterFS Service
      systemd:
        name: glusterd
        enabled: yes
        state: started

...
