- hosts: all

  become: true

  tasks:

    - name: generate tendrl inventory
      template:
        src: tendrl-inventory.j2
        dest: /home/vagrant/tendrl-inventory

    - name: copy site.yml from tendrl samples
      template:
        src: tendrl-site.yml.j2
        dest: /home/vagrant/tendrl-site.yml
        block_start_string: "[%"
        block_end_string: "%]"
        variable_start_string: "[["
        variable_end_string: "]]"

    - name: remove generic machine id
      file:
        path: /etc/machine-id
        state: absent

    - name: re-generate machine id
      shell: systemd-machine-id-setup
