---

- hosts: gluster-servers

  become: true

  tasks:
    - name: add EPEL
      yum:
        name: epel-release
        state: present

    - name: add copr
      yum:
        name: yum-plugin-copr
        state: present

    - name: add gluster repo
      yum:
        name: centos-release-gluster
        state: present

    - name: Install GlusterFS Server
      yum:
        name: glusterfs-server
        state: present

    - name: Enable GlusterFS Service
      systemd:
        name: glusterd
        enabled: yes
        state: started

...
