---
- hosts: gluster-servers
  user: vagrant
  become: yes
  vars:
    configure_firewalld_for_tendrl: false
    etcd_fqdn: ETCD.host
    graphite_fqdn: GRAPHITE.host
  roles:
    - tendrl-ansible.tendrl-copr
    - tendrl-ansible.tendrl-storage-node
